/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.48
 * Generated at: 2021-09-03 10:48:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.templates.public_.inc;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.bean.News;
import model.dao.NewsDAO;
import model.bean.Category;
import java.util.ArrayList;
import model.dao.CategoryDAO;

public final class left_002dbar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.dao.NewsDAO");
    _jspx_imports_classes.add("model.dao.CategoryDAO");
    _jspx_imports_classes.add("model.bean.Category");
    _jspx_imports_classes.add("model.bean.News");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<div class=\"left-bar\">\r\n");
      out.write("<div style=\"background-color:red; height=20px; width:100px\"></div>	\r\n");
      out.write("				<div class=\"cat\">\r\n");
      out.write("					<span>Danh mục việc làm <span>\r\n");
      out.write("					<ul>\r\n");
      out.write("					");
	String active = request.getParameter("active");
					  	CategoryDAO categoryDAO = new CategoryDAO();
					  	ArrayList<Category> categories = categoryDAO.getItems();
					  	if(categories != null && categories.size() > 0){
					  		for(Category item: categories){
					  
      out.write("<li class=\"");
if(!active.equals(String.valueOf(item.getId()))){ out.print("noactive");}else {out.print("active");} 
      out.write("\">\r\n");
      out.write("							<a href=\"");
      out.print(request.getContextPath());
      out.write("/cat?cat_id=");
      out.print(item.getId());
      out.write("&active=");
      out.print(item.getId());
      out.write('"');
      out.write('>');
      out.write(' ');
      out.print(item.getName() );
      out.write("</a>\r\n");
      out.write("						</li>\r\n");
      out.write("					");
} }
      out.write("</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class= \"newjob\">\r\n");
      out.write("					<span>Tuyển dụng mới <span>\r\n");
      out.write("						<ul>\r\n");
      out.write("						");

							NewsDAO newsDAO = new NewsDAO();
							ArrayList<News> left_barnews = newsDAO.getItemsTop(4);
							if(left_barnews != null && left_barnews.size() > 0){
								for(News item: left_barnews){
						
      out.write("<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/detail?id=");
      out.print(item.getId());
      out.write("&active=");
      out.print(item.getCategory().getId());
      out.write('"');
      out.write('>');
      out.print(item.getTitle() );
      out.write("</a> <p>");
      out.print(item.getDate() );
      out.write("</p></li>\r\n");
      out.write("						");
} }else{ 
      out.write("<ul> Không có dữ liệu</ul>\r\n");
      out.write("						");
} 
      out.write("</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
